version:  '3.4'

services:
  wait:
    image: dokku/wait

  php:
    build:
      context: .
      dockerfile: build/docker/php/Dockerfile
    volumes:
      - .:/srv/app
      - ./php-fpm:/var/run/php
    tty: true
    stdin_open: true

  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - ./build/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/srv/app
      - ./php-fpm:/var/run/php
    depends_on:
      - php

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-root}
    ports:
      - "5432:5432"